### ISSUE TITLE
apigateway.RestAPI: Restricting multiple Authorizers

### ISSUE THREAD

**Issue by abdulsamisahil** [pulumi/pulumi-aws-apigateway#156] opened 2024-07-05 14:43 UTC
## Pulumi: apigateway.RestAPI restricting multiple authorizers to a unified authorizer across all routes. 

- Vote on this issue by adding a 👍 reaction

## Issue details

Multiple Authorizers issue in apigateway.RestAPI: I'm trying to create an API Gateway using "@pulumi/aws-apigateway" with the following code:

```bash

import { AuthorizerArgs } from "@pulumi/aws-apigateway/types/input";
import * as apigateway from "@pulumi/aws-apigateway";
import { authorizerLambda } from "./utils"

// Define the common authorizer
const commonAuthorizer: AuthorizerArgs = {
    parameterName: "Authorization",
    parameterLocation: "header",
    identityValidationExpression: "^Bearer [-0-9a-zA-Z._]*$",
    authType: "custom",
    type: "token",
    identitySource: ["method.request.header.Authorization"],
    handler: authorizerLambda,
    authorizerResultTtlInSeconds: 600,
};

// Create the API Gateway with routes
const api = new apigateway.RestAPI("test-api", {
    stageName: "v1",
    routes: [
        {
            path: "/route1",
            method: "PUT",
            eventHandler: route1PutLambdaFunction,
            authorizers: [commonAuthorizer],
        },
        {
            path: "/route1",
            method: "DELETE",
            eventHandler: route1DeleteLambdaFunction,
            authorizers: [commonAuthorizer],
        },
        {
            path: "/route2",
            method: "PUT",
            eventHandler: route2PutLambdaFunction,
            authorizers: [commonAuthorizer],
        },
        {
            path: "/route3",
            method: "PUT",
            eventHandler: route3PutLambdaFunction,
            authorizers: [commonAuthorizer],
        },
        // Add more routes as needed
    ],
});

```

### Affected area/feature

Issue: Even though I define a single commonAuthorizer, `pulumi up` creates a separate authorizer for each route. If there are 10 routes, it generates 10 different authorizers, roles, and permissions. This duplication causes exceed the default api gateway authorizers limit of 10.

Expected Behavior: It would be optimistic to find and release a workaround this, using `apigateway.RestAPI` and `routes: RouteArgs[]` with `authorizers: AuthorizerArgs[]` and a flexability to restrict it to a single reusable authorizer across all multiple routes.

Actual Behavior: Each route creates its own authorizer, resulting in unnecessary duplication of gateway authorizers, roles and permissions, and deployment hangs with more than 10 routes.

QA: Is there any currect workaround to address this?

**Comment by flostadler** [comment] 2024-07-08 12:43
Sorry that you're running into this @abdulsamisahil! It should reuse the authorizer when specifying the `authorizerName` in the `AuthorizerArgs`.
I just tried doing that, but it causes exceptions:
```
Error: Two different authorizers using the same name: jwt-rsa-custom-authorizer: Error: Two different authorizers using the same name: jwt-rsa-custom-authorizer
```

I'll continue investigating what's going wrong here

**Comment by abdulsamisahil** [comment] 2024-07-08 13:56
> Sorry that you're running into this @abdulsamisahil! It should reuse the authorizer when specifying the `authorizerName` in the `AuthorizerArgs`. I just tried doing that, but it causes exceptions:
> 
> ```
> Error: Two different authorizers using the same name: jwt-rsa-custom-authorizer: Error: Two different authorizers using the same name: jwt-rsa-custom-authorizer
> ```
> 
> I'll continue investigating what's going wrong here

Yes, you're right. I did that but it is throwing that unique name requiring error during the creation of authorizer because it attempts and is in fact creating several authorizers based on the length of the routes array.

**Comment by flostadler** [comment] 2024-07-08 17:59
I found the root cause of the issue. This equality check here will never be truthy: https://github.com/pulumi/pulumi-aws-apigateway/blob/main/provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts#L1010

Those inputs come in via GRPC into the provider and get re-assembled, thus all authorizer always get different references. Even if their underlying values are equal. Switching this out with a deep equals check is not trivial because parts of the underlying values are outputs which cannot be easily compared. We might be able to do the intended verification by resolving all authorizers and then comparing the ones that have the same name.

**Comment by abdulsamisahil** [comment] 2024-07-09 07:17
> I found the root cause of the issue. This equality check here will never be truthy: https://github.com/pulumi/pulumi-aws-apigateway/blob/main/provider/cmd/pulumi-resource-aws-apigateway/apigateway/api.ts#L1010
> 
> Those inputs come into the provider via GRPC and get re-assembled as objects, thus all authorizer always get different references. Even if their underlying values are equal. Switching this out with a deep equals check is not trivial because parts of the underlying values are outputs which cannot be easily compared. We might be able to do the intended verification by resolving all authorizers and then comparing the ones that have the same name.

Thanks @flostadler for identifying the cause. I know fixing this is complicated because the object includes parts that are hard to compare.

 How should we proceed to resolve this issue and use a single authorizer using these types and RestAPI? What are the next steps?

**Comment by flostadler** [comment] 2024-07-09 11:24
@abdulsamisahil I'm trying to make the intended verification (no authorizers with the same name, but different config) work. If this ends up not being possible, we'll have to remove that verification.

I'll keep the issue here updated with my findings and when I create a PR to fix it.

**Comment by flostadler** [comment] 2024-07-11 15:00
I just merged the fix for this! Will kick off the release asap.

**Closed** 2024-07-11 14:59 UTC
Labels: impact/usability, kind/bug

**Comment by abdulsamisahil** [comment] 2024-07-31 09:21
Very Important: If you are using a single authorizer across multiple routes, you must disable caching on the authorizer object by setting `authorizerResultTtlInSeconds: 0`. Failing to do so will result in API Gateway responses of 404 with `{"message": "404 Not found"}`.

This is the number of seconds during which the resulting IAM policy, allow or deny is cached.
